# Generated by Django 5.1 on 2024-09-09 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombCategoria', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('idPedido', models.AutoField(primary_key=True, serialize=False)),
                ('fechaPedido', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pedido',
            },
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('idProveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombProveedor', models.CharField(max_length=25)),
                ('telefProveedor', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'proveedores',
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('idSucursal', models.AutoField(primary_key=True, serialize=False)),
                ('nombSucursal', models.CharField(max_length=25)),
                ('telefSucursal', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'sucursal',
            },
        ),
        migrations.CreateModel(
            name='Tipo_Pedido',
            fields=[
                ('idTipoPedido', models.AutoField(primary_key=True, serialize=False)),
                ('nombPedido', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'tipo_Pedido',
            },
        ),
        migrations.CreateModel(
            name='Tipo_Producto',
            fields=[
                ('idTipo', models.AutoField(primary_key=True, serialize=False)),
                ('nombTipo', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'tipo_Producto',
            },
        ),
        migrations.CreateModel(
            name='Despacho',
            fields=[
                ('idDespacho', models.AutoField(primary_key=True, serialize=False)),
                ('fechaDespacho', models.DateField()),
                ('idPedido_fk', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_datos.pedido')),
            ],
            options={
                'db_table': 'despacho',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.AutoField(primary_key=True, serialize=False)),
                ('nombProd', models.CharField(max_length=25)),
                ('unidadProducto', models.CharField(blank=True, max_length=25, null=True)),
                ('idCategoria_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_datos.categoria')),
                ('idProveedor_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_datos.proveedores')),
                ('idTipo_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_datos.tipo_producto')),
            ],
            options={
                'db_table': 'producto',
            },
        ),
        migrations.CreateModel(
            name='Produccion',
            fields=[
                ('idProduccion', models.AutoField(primary_key=True, serialize=False)),
                ('cantProduccion', models.IntegerField()),
                ('fechaProduccion', models.DateField()),
                ('idProdTerminado_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_datos.producto')),
            ],
            options={
                'db_table': 'produccion',
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('idInventario', models.AutoField(primary_key=True, serialize=False)),
                ('cantInventario', models.IntegerField()),
                ('fechaInventario', models.DateField()),
                ('idProd_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_datos.producto')),
            ],
            options={
                'db_table': 'inventario',
            },
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('idIngreso', models.AutoField(primary_key=True, serialize=False)),
                ('cantIngreso', models.IntegerField()),
                ('fechaIngreso', models.DateField()),
                ('idProd_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_datos.producto')),
            ],
            options={
                'db_table': 'ingreso',
            },
        ),
        migrations.CreateModel(
            name='Detalle_Produccion',
            fields=[
                ('idDetalleProduccion', models.AutoField(primary_key=True, serialize=False)),
                ('cantidadUsada', models.IntegerField()),
                ('idProd_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_datos.produccion')),
                ('idMateriaPrima_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_datos.producto')),
            ],
            options={
                'db_table': 'detalle_Produccion',
            },
        ),
        migrations.CreateModel(
            name='Detalle_Pedido',
            fields=[
                ('idDetalleP', models.AutoField(primary_key=True, serialize=False)),
                ('cantidadPedido', models.IntegerField()),
                ('cantidadDespacho', models.IntegerField()),
                ('idPed_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_datos.pedido')),
                ('idProd_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_datos.producto')),
            ],
            options={
                'db_table': 'detalle_Pedido',
            },
        ),
        migrations.AddField(
            model_name='pedido',
            name='idSucursal_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_datos.sucursal'),
        ),
        migrations.CreateModel(
            name='Devoluciones',
            fields=[
                ('idDevolucion', models.AutoField(primary_key=True, serialize=False)),
                ('cantDevuelta', models.IntegerField()),
                ('fechaDevolucion', models.DateField()),
                ('motivoDevolucion', models.TextField(blank=True, max_length=100, null=True)),
                ('idProd_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_datos.producto')),
                ('idSuc_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_datos.sucursal')),
            ],
            options={
                'db_table': 'devoluciones',
            },
        ),
        migrations.AddField(
            model_name='pedido',
            name='idTipoPedido_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_datos.tipo_pedido'),
        ),
    ]
