# Generated by Django 5.1 on 2025-03-27 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_datos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Egreso',
            fields=[
                ('idEgreso', models.AutoField(primary_key=True, serialize=False)),
                ('cantEgreso', models.IntegerField()),
                ('fechaEgreso', models.DateField()),
                ('idProd_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_datos.producto')),
            ],
            options={
                'db_table': 'egreso',
            },
        ),
    ]
