# Generated by Django 5.1 on 2025-04-09 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_datos', '0002_egreso'),
    ]

    operations = [
        migrations.AddField(
            model_name='egreso',
            name='usuarioEgreso',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='ingreso',
            name='usuarioIngreso',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
